version: "3"

services:
  tool_database:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - tool-postgres:/var/lib/postgresql/data/
    networks:
      - sparky
    environment:
      POSTGRES_DB: tool
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

networks:
  sparky:
    driver: bridge

volumes:
  tool-postgres:
    driver: local