version: "3"

services:
  tool_database:
    image: postgres:15.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tool
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
  tool_database_old:
    image: postgres:15.4-alpine
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: tool
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

volumes:
  data: